### ISSUE TITLE
7Span: PEMM website architecture

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#108]
7/17/23
The pages of the PEMM website are listed below. Tasks for 7Span are described.

### Home
![0 Home page](https://github.com/PrincetonPEMM/pemm-issues/assets/56000106/d3d529b0-f601-4d9d-bc65-d7b469f07e46)
<img width="646" alt="0 Home page Featured Design" src="https://github.com/PrincetonPEMM/pemm-issues/assets/56000106/99e00c38-6517-4837-9153-295dbbbdeb21">
Design Note: This is the only page where the images go all the way to the top and the logo and navigation bar are in white

Home page: https://www.ethiopicmary.com 
- [ ] Dynamic page: Correct some things. See ticket PrincetonPEMM/pemm-issues#107 for bugs in design
- [ ] Navigation bar: Dropdowns probably need work
- [ ] Featured stories, paintings, manuscripts
- [ ] Footer: Correct some things. See tickets for bugs:
- [ ] PrincetonPEMM/pemm-issues#86 
- [ ] PrincetonPEMM/pemm-issues#64

**Comment by WendyLBelcher** [comment]
### About pages (3 static pages)
People page: https://www.ethiopicmary.com/about/people
- [ ] Static page: copy and paste in the wording in ticket ??

Mission page: https://www.ethiopicmary.com/about/mission
- [ ] Static page: copy and paste in the wording in ticket ??

Connect page: https://www.ethiopicmary.com/about/connect
- [ ] Static page: copy and paste in the wording in ticket ??

**Comment by WendyLBelcher** [comment]
### Research tools pages (7 static pages; 2 dynamic pages for later development)
Arabic manuscripts page: https://www.ethiopicmary.com/research/arabic-manuscripts
- [ ] Static page: copy and paste in the wording in ticket ??

Arabic stories page: https://www.ethiopicmary.com/research/arabic-stories
- [ ] Static page: copy and paste in the wording in ticket ??

Interchangeable spellings of Ethiopic Terms page: https://www.ethiopicmary.com/research/spellings
- [ ] Static page: copy and paste in the wording in ticket ??

Research Posts page: https://www.ethiopicmary.com/research/research-posts
- [ ] Static page: copy and paste in the wording in ticket ??

Macomber Handlist page: https://www.ethiopicmary.com/research/macomber
- [ ] Static page: copy and paste in the wording in ticket ??
- [ ] Update web address from `macomber `to `macomber-handlist`

List of Repositories page: https://www.ethiopicmary.com/research/repositories
- [ ] Static page: copy and paste in the wording in ticket #105 

Bibliography page: https://www.ethiopicmary.com/research/bibliography
- [ ] Static page: copy and paste in the wording in ticket ?? 

Maps page: https://www.ethiopicmary.com/research/maps
- [ ] Dynamic page: ignore for now

Incipit tool page: https://www.ethiopicmary.com/research/incipit-tool
- [ ] Dynamic page, develop full search application later

**Comment by WendyLBelcher** [comment]
### Story pages (2 dynamic pages, both are already created)
Story index page: https://www.ethiopicmary.com/stories
- [ ] Dynamic page: Correct some things. See ticket ?? for bugs in design 

Story detail page: https://www.ethiopicmary.com/stories/0000 
- [ ] Dynamic page: Correct some things. See ticket ?? for bugs in design
- [ ] We have ~1000 stories, so one page for each of the `canonical_story_unique_id` numbers
- [ ] Web addresses for each story should use the `pemm_theme_id_number` field; e.g., https://www.ethiopicmary.com/stories/1111

**Comment by WendyLBelcher** [comment]
### Manuscript pages  (2 dynamic pages, only 1 has been created already)
Manuscript index page: https://www.ethiopicmary.com/manuscripts
- [ ] Dynamic page: Create a dynamic page using the `Manuscript` table. See ticket ?? for fields and layout

Manuscript detail page: https://www.ethiopicmary.com/manuscripts/0000 
- [ ] Dynamic page: Correct some things. See ticket ?? for bugs in design 
- [ ] We have ~1000 manuscripts, so one page for each of the `Manuscript` table `manuscript_unique_id` numbers
- [ ] Web addresses for each manuscript should use the `web_page_address` field; e.g., https://www.ethiopicmary.com/manuscripts/BLorient520

**Comment by WendyLBelcher** [comment]
### Painting pages  (4 dynamic pages, only 1 has been created already)
Painting index page: https://www.ethiopicmary.com/paintings 
- [ ] Dynamic page: Correct some things. See ticket #101 for bugs in design 

Paintings by Manuscript page: https://www.ethiopicmary.com/paintings/manuscript/0000 
- [ ] Dynamic page: Create a dynamic page using the `Paintings `table. See ticket ?? for fields and layout
- [ ] Update web address https://www.ethiopicmary.com/paintings-by-manuscript/ [if possible to do so]
- [ ] We have between 80 and 300 manuscripts with paintings, so one page for each of those manuscripts
- [ ] Web addresses for each manuscript should use the `Manuscript `table  `web_page_address` field; e.g., https://www.ethiopicmary.com/manuscripts/paintings-by-manuscript/BLorient520

Paintings by Story page:  https://www.ethiopicmary.com/paintings/story/0000
- [ ] Dynamic page: Create a dynamic page using the `Paintings `table. See ticket ?? for fields and layout 
- [ ] Update web address https://www.ethiopicmary.com/paintings-by-story/ [if possible to do so]
- [ ]  We have ~100 stories with paintings, so one page for each of those stories
- [ ] Web addresses for each story should use the `Canonical Story` table `pemm_theme_id_number` field; e.g., https://www.ethiopicmary.com/paintings-by-story/1111

Painting detail page: https://www.ethiopicmary.com/paintings/0000
- [ ] Dynamic page: Create a dynamic page using the `Paintings `table. See ticket ?? for fields and layout
- [ ] We have ~2000 paintings, so one page for each of those paintings
- [ ] Web addresses for each painting should use the  `Paintings `table `painting_unique_id` field; e.g., https://www.ethiopicmary.com/paintings/1250
