### ISSUE TITLE
Paintings by Story Page

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#19]
Anisa showed us two Painting Index pages. 

One had a faceted search, for all 2,000 images, which we definitely want. 

The other was organized differently, showing just one representative painting per story. Since not all stories have paintings, that would be just 110 paintings.  It would perhaps be just thumbnails (?) and with only the story title (no manuscript, folio, episode information). Then, below the story title, one would see a clear button that said "See all 20 images for this story." So people would know that this was a sample.

Having a page with just 110 images solves a problem with the faceted search page. On that page, the paintings will need to be organized by story. That means that, given pagination, the first one or two pages will be a stream of variations on the same three paintings. That is, the user will see 10 images of the bishops handing over the book to Mary, 10 of Mary preparing garments for the bishop, and 10 of the next bishop dying. That will give the wrong impression of the paintings, that they are all of the same thing. 

But I wasn't sure how we could have two pages. We don't have two pages for manuscripts or stories. We discussed the possibility of having it be a hide/view option but I think Henok said that would be tough.

**Comment by WendyLBelcher** [comment]
Anisa showed us two Painting Index pages. One had a faceted search, which we definitely want. The other was organized differently, showing just one representative painting per story. I kind of liked the second, but I wasn't sure how that would work. We don't have two for manuscripts or stories. We discussed the possibility of having it be a hide/view option but I think Henok said that would be tough.

**Comment by henokalem** [comment]
<img width="541" alt="featured_paintings_page" src="https://user-images.githubusercontent.com/17439057/159061995-2c44bcc1-3edd-439a-b590-d8038ea91ad0.png">

**Comment by WendyLBelcher** [comment]
- [ ] One representative painting per story (which one is the Featured Painting for a particular story will be signaled on the paintings spreadsheet, so you will have that information). 
- [ ] 
- [ ] Underneath each painting is a black box and it has only the story title (no manuscript, folio, episode information). 
- [ ] 
- [ ] Then, below the story title, one would see a clear button that said "See all 20 images for this story." That button takes you to the Painting Detail Page.
- [ ] 
- [ ] The paintings/stories will be in Macomber ID Number order. 
- [ ] 
- [ ] No pagination. We have 110 stories that have paintings. (We can always add it later.)
