### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#23]
The PEMM About page will have links to several static pages.

**Comment by WendyLBelcher** [comment]
The static pages will be:

- [ ] - `Our Mission` [Just text about the Miracles of Mary, with nothing else but the navigation bar and footer]
- [ ] - `Our Team` [Just a list of people who work (or used to work) on PEMM, with nothing else but the navigation bar and footer]
- [ ] - `Our Partners` [Just a list of institutions, with links, who provided materials or research support PEMM, with nothing else but the navigation bar and footer]
- [ ]  `Our Funders` [Just a list of funders, with links, of PEMM, with nothing else but the navigation bar and footer]
- [ ] - `Our History` [Just a history of when the project began and how it went, with nothing else but the navigation bar and footer]
- [ ] - Volunteer [Maybe this isn't a separate page, but just some information on the `About` page about what we need in terms of volunteering]
- [ ] - `Media Coverage` [Just the headlines, with a brief summary, of stories about PEMM, with nothing else but the navigation bar and footer]
- [ ] - `Project Updates` [Just the newsletters, called Updates, with nothing else but the navigation bar and footer]
- [ ] - `Events & Workshops` [This might be better on the About page, since I'm not sure if we will have events and workshops, although Mehari and Dawit are willing]

**Comment by WendyLBelcher** [comment]
The About page will have links to the following static pages:

- [ ] - `Our Mission` [Just text about the Miracles of Mary, with nothing else but the navigation bar and footer]
- [ ] - `Our Team` [Just a list of people who work (or used to work) on PEMM, with nothing else but the navigation bar and footer]
- [ ] - `Our Partners` [Just a list of institutions, with links, who provided materials or research support PEMM, with nothing else but the navigation bar and footer]
- [ ]  `Our Funders` [Just a list of funders, with links, of PEMM, with nothing else but the navigation bar and footer]
- [ ] - `Our History` [Just a history of when the project began and how it went, with nothing else but the navigation bar and footer]
- [ ] - Volunteer [Maybe this isn't a separate page, but just some information on the `About` page about what we need in terms of volunteering]
- [ ] - `Media Coverage` [Just the headlines, with a brief summary, of stories about PEMM, with nothing else but the navigation bar and footer]
- [ ] - `Project Updates` [Just the newsletters, called Updates, with nothing else but the navigation bar and footer]
- [ ] - `Events & Workshops` [This might be better on the About page, since I'm not sure if we will have events and workshops, although Mehari and Dawit are willing]

**Comment by WendyLBelcher** [comment]
Somewhere on the About page, I need to list something about Scope. For instance, we loaded all EMML names Macomber used in his handlist, even if there was a single miracle cataloged. Then we also made sure we had all EMML mss from the Delamarter list. But, "we did not add the other EMML mss because we thought we already had a disproportional regional presence of these mss, and we rather wanted to add other repositories."

**Comment by WendyLBelcher** [comment]
The content of the Our Mission page (hyperlinks didn't come through:
The Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary digital humanities project (PEMM) is a comprehensive resource for the 1,000+ miracle stories about the Virgin Mary in Ethiopia, Eritrea, and Egypt, and preserved in Gəˁəz between 1300 and the present.
PEMM was launched in March 2018 to catalog and translate the Ethiopian compilation text that contains these stories, called Täˀammərä Maryam (Miracles of Mary). 
The project is aimed at creating a resource for all students and scholars interested in folklore and to the Ethiopian Orthodox Church community. It provides Ethiopians with digital access to their patrimony, while raising general awareness about the beauty, breadth, and variety of these vital works of early African literature.
Drawing on manuscripts from the exceptional collection of Täˀammərä Maryam in Princeton’s Rare Books and Special Collections, PEMM collects information about these miracle tales to enable better scholarship on their contents across regions, languages, and time. Its base is the painstaking work of miracle story identifications that William F. Macomber [link] did in the 1980s, itself compiling the work of previous scholars.
Conceived and directed by Prof. Wendy Laura Belcher, PEMM was developed in partnership with Princeton’s Center for Digital Humanities, along with PEMM’s first project manager, Evgeniia Lambrinaki, and an incredible team of scholars, programmers, volunteers, [link to Our Team] and partners. [link to our Partners] 
The painting on this page is from Princeton Ethiopic manuscript no. 65, of the Bishop Hildefonsus showing Mary the book of her miracles that he wrote (image 21).

**Comment by WendyLBelcher** [comment]
The content of Our Team page is at https://pemm.princeton.edu/project-team/. Include it all, except move the Institutional Partners to the Our Partners page.

**Comment by WendyLBelcher** [comment]
The content of Our Partner page is at https://pemm.princeton.edu/project-team/. under the title Institutional Partners (which needs to move to Our Partners page.)

**Comment by WendyLBelcher** [comment]
The content of Our Funders page is at https://pemm.princeton.edu/pemm-funding/. Include all of it

**Comment by WendyLBelcher** [comment]
Individual content pages need to be made for each team member. The content of each page is at:
https://pemm.princeton.edu/evgeniia-lambrinaki/
https://pemm.princeton.edu/jeremy-brown/
https://pemm.princeton.edu/mehari-worku/
https://pemm.princeton.edu/dawit-muluneh/
https://pemm.princeton.edu/henok-alem/
https://pemm.princeton.edu/bret-windhauser/
https://pemm.princeton.edu/taylor-eggan/
https://pemm.princeton.edu/vitagrazia-pisani/

**Comment by WendyLBelcher** [comment]
A design for the news page
[PEMM News redesign.pdf](https://github.com/PrincetonPEMM/pemm-issues/files/9302921/PEMM.News.redesign.pdf)
