### ISSUE TITLE
Story Index Page

### ISSUE THREAD

**Issue by jamiefolsom** [PrincetonPEMM/pemm-issues#8]
- [x] **Search Bar & Sort Header Columns [a]**

Complete guide to this section is documented in separate ticket, #37

- [x] **Title View & Detail View [b]**

Complete guide to this section is documented in separate ticket, #38 

- [x] **Links to Story Detail Page [c]**

Complete guide to this section is documented in separate ticket, #40 

- [x] **Faceted Search [d]**

Complete guide to this section is documented in separate ticket, #21
